name: Mac

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache Boost
      id: cache-boost
      uses: actions/cache@v1
      with:
        path: boost_1_74_0/installdir
        key: ${{ runner.os }}-boost_1_74_0
    - name: Install Boost
      brew install boost
    - name: cmake
      run: |
        cmake -E make_directory build
        cd build
        cmake ..
    - name: Compile
      working-directory: build
      run: cmake --build . -j2
    - name: Test
      working-directory: build
      run: ctest -j2
